#!/usr/bin/env python

import pandas
import h5py

# read in test data
data = pandas.read_csv("test.csv")
# write out the data to test
data.to_csv("new.csv", index=False)


with h5py.File("new.hdf5", "w") as f:
    f.create_dataset("database", data)


