#!/bin/bash

WKDIR=testing/scratch/url

echo "Creating temporary work area at $WKDIR" 
echo ""
echo "To use:"
echo "  pushd $WKDIR"
echo "  open test-url.html"
echo "  python -m cinemasci.server --port 8200 --viewer view --data data/sphere.cdb"
echo ""

mkdir testing/scratch > /dev/null 2>&1
mkdir  $WKDIR > /dev/null 2>&1

cp -rf cinemasci $WKDIR
cp -rf testing/data $WKDIR 
cp testing/test-url.html $WKDIR 
cp testing/test-function.py $WKDIR

