#!/bin/bash

WKDIR=testing/scratch/url

echo "Creating temporary work area at $WKDIR" 
echo ""
echo "To use:"
echo "  pushd $WKDIR"
echo "  open test-url.html"
echo "  ./start-test-servers" 
echo ""

rm -rf testing/scratch

mkdir testing/scratch > /dev/null 2>&1
mkdir  $WKDIR > /dev/null 2>&1

cp -rf cinemasci $WKDIR
cp -rf testing/data $WKDIR 
cp testing/start-test-servers $WKDIR 
cp testing/test-url.html $WKDIR 
cp testing/test-function.py $WKDIR

