#!/bin/bash

# clean
echo "Cleaning test area"
rm -rf testing/scratch

# install a scratch database
CL_PATH="testing/scratch/install/commandline"
HTMLFILE="$CL_PATH/index.html"
mkdir testing/scratch
mkdir testing/scratch/install
mkdir $CL_PATH 
printf "<html>\n" > $HTMLFILE

ITYPES="local remote"
VIEWERS="explorer view simple"
NUMDBS="one two"
echo "Creating viewer installs ..."
for itype in $ITYPES; do
    echo "    $itype"
    TPATH=$CL_PATH/$itype
    mkdir $TPATH

    for viewer in $VIEWERS; do
        VPATH=$TPATH/$viewer
        mkdir $VPATH

        for num in $NUMDBS; do
            NPATH=$VPATH/$num
            mkdir $NPATH

            # copy the data
            cp -rf testing/data/sphere.cdb $NPATH 
            cp -rf testing/data/sedov1.cdb $NPATH 
            cp -rf testing/data/sedov2.cdb $NPATH 

            # write an entry in the testplan html file
            HREF="$itype/$viewer/$num/cinema_${viewer}.html"
            printf "<p><a href=\"$HREF\">$HREF</a></p>\n" >> $HTMLFILE

            if [ "$num" = "one" ]; then
                # do a python-based install for a single database
                python3 -m cinemasci.install --path $NPATH --database sphere.cdb --viewer $viewer --type $itype
            else
                # do a python-based install for two databases
                python3 -m cinemasci.install --path $NPATH --database sedov1.cdb sedov2.cdb --viewer $viewer --type $itype
            fi
        done
    done
done
printf "</html>\n" >> $HTMLFILE
