#!/bin/bash

mkdir testing/scratch
pushd testing/scratch

mkdir pynb
pushd pynb

cp -rf ../../../cinemasci .
cp -rf ../../data/ttk_extracts.cdb .
cp     ../../data/cisviewer/* .

jupyter notebook ttk-extracts.ipynb

popd
