#!/bin/bash

mkdir testing/scratch
pushd testing/scratch

mkdir pynb
pushd pynb

cp -rf ../../../cinemasci .
cp -rf ../../data/pantheon_ascent-clover.cdb .
cp     ../../data/cisviewer/* .

jupyter notebook ascent-clover.ipynb

popd
