#!/bin/bash

mkdir testing/scratch
pushd testing/scratch

mkdir pynb
pushd pynb

cp -rf ../../../cinemasci .
cp -rf ../../data/cis.cdb .
cp     ../../data/cisviewer/* .

jupyter notebook cisviewer.ipynb

# if testing ascent conversion
# cp -rf ../../../bin/pantheon.cdb .
# jupyter notebook ascent.ipynb

popd
