#!/bin/bash

mkdir testing/scratch
pushd testing/scratch

mkdir pynb
pushd pynb

cp -rf ../../../cinemasci .
cp -rf ../../data/paraview_extracts.cdb .
cp     ../../data/cisviewer/* .

jupyter notebook paraview-extracts.ipynb

popd
